import re
from datetime import datetime, timezone


def _utc_iso(dt: datetime | None) -> str:
    if not dt:
        return ""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.isoformat()

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from auth import get_current_user
from database import get_db
from models import Agent, AgentSnapshot, AuditEvent, ThreatFinding, User
from schemas import (
    AgentCreate,
    AgentOut,
    AgentSnapshotOut,
    AgentUpdate,
    AuditEventOut,
    PolicySchema,
)

router = APIRouter(prefix="/api/agents", tags=["agents"])

LIFECYCLE_ORDER = ["dev", "staging", "prod", "deprecated"]
PROTECTION_ORDER = ["unprotected", "awaiting_event", "protected"]

# Hash-named / autogenerated trace artefacts that aren't real agents.
_HEX32 = re.compile(r"^[0-9a-f]{32}$", re.I)
_KICKOFF = re.compile(r"kickoff$", re.I)


def _is_trace_junk(agent: Agent) -> bool:
    """A trace-id-named record (e.g. '69590eae...' or 'Crew_xxx.kickoff'), not a real agent."""
    name = (agent.name or "").strip()
    slug = (agent.slug or "").strip()
    if _HEX32.match(name) or _HEX32.match(slug):
        return True
    if _KICKOFF.search(slug) or _KICKOFF.search(name):
        return True
    return False


def _dup_score(agent: Agent) -> tuple:
    """Higher tuple = better record to keep when de-duplicating a slug group."""
    prot = PROTECTION_ORDER.index(agent.protection_status) if agent.protection_status in PROTECTION_ORDER else 0
    life = LIFECYCLE_ORDER.index(agent.lifecycle) if agent.lifecycle in LIFECYCLE_ORDER else 0
    deps = agent.dependencies or {}
    dep_count = sum(len(deps.get(k, []) or []) for k in ("models", "tools", "dataSources", "agents"))
    threat_count = len(agent.threats or [])
    audit_count = len(agent.audit_log or [])
    has_owner = 1 if agent.owner else 0
    # created_at as a tiebreaker: keep the oldest (negative timestamp sorts later=smaller)
    created = -(agent.created_at.timestamp() if agent.created_at else 0)
    return (prot, life, has_owner, dep_count, threat_count, audit_count, created)


def _agent_to_out(a: Agent) -> dict:
    return {
        "id": a.id,
        "name": a.name,
        "slug": a.slug,
        "description": a.description,
        "systemPrompt": a.system_prompt,
        "tags": a.tags or [],
        "platforms": a.platforms or [],
        "createdAt": a.created_at.isoformat() if a.created_at else "",
        "userId": a.user_id,
        "owner": a.owner,
        "team": a.team,
        "oncall": a.oncall,
        "capability": a.capability,
        "version": a.version,
        "lifecycle": a.lifecycle,
        "dependencies": a.dependencies,
        "accessScope": a.access_scope,
        "guardrails": a.guardrails,
        "compliance": a.compliance,
        "approvedBy": a.approved_by,
        "approvedAt": a.approved_at.isoformat() if a.approved_at else None,
        "capabilitySpec": a.capability_spec,
        "riskTier": a.risk_tier,
        "dataClassifications": a.data_classifications,
        "sourcePlatform": a.source_platform,
        "protectionStatus": a.protection_status,
        "captureStyle": a.capture_style,
        "firstInstrumentedAt": a.first_instrumented_at.isoformat() if a.first_instrumented_at else None,
        "policy": a.policy,
        "auditLog": [
            {
                "id": e.id,
                "at": e.at.isoformat() if e.at else "",
                "actor": e.actor,
                "action": e.action,
                "from": e.from_state,
                "to": e.to_state,
                "summary": e.summary,
                "snapshotId": e.snapshot_id,
            }
            for e in (a.audit_log or [])
        ],
        "snapshots": [
            {"id": s.id, "at": s.at.isoformat() if s.at else "", "data": s.data}
            for s in (a.snapshots or [])
        ],
        "threats": [
            {
                "id": t.id,
                "control": t.control,
                "agentId": t.agent_id,
                "severity": t.severity,
                "summary": t.summary,
                "detail": t.detail,
                "detectedAt": _utc_iso(t.detected_at),
                "principal": t.principal,
            }
            for t in (a.threats or [])
        ],
    }


def _snapshot_data(a: Agent) -> dict:
    return {
        "id": a.id,
        "name": a.name,
        "slug": a.slug,
        "description": a.description,
        "systemPrompt": a.system_prompt,
        "tags": a.tags,
        "platforms": a.platforms,
        "createdAt": a.created_at.isoformat() if a.created_at else "",
        "userId": a.user_id,
        "owner": a.owner,
        "team": a.team,
        "oncall": a.oncall,
        "capability": a.capability,
        "version": a.version,
        "lifecycle": a.lifecycle,
        "dependencies": a.dependencies,
        "compliance": a.compliance,
        "riskTier": a.risk_tier,
        "dataClassifications": a.data_classifications,
        "protectionStatus": a.protection_status,
        "policy": a.policy,
    }


def _eager():
    return [
        selectinload(Agent.audit_log),
        selectinload(Agent.snapshots),
        selectinload(Agent.threats),
    ]


@router.get("/", response_model=list[AgentOut])
async def list_agents(
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
    lifecycle: str | None = Query(None),
    team: str | None = Query(None),
):
    stmt = select(Agent).where(Agent.user_id == user.id).options(*_eager())
    if lifecycle:
        stmt = stmt.where(Agent.lifecycle == lifecycle)
    if team:
        stmt = stmt.where(Agent.team == team)
    stmt = stmt.order_by(Agent.created_at.desc())
    result = await db.execute(stmt)
    return [_agent_to_out(a) for a in result.scalars().all()]


@router.post("/", response_model=AgentOut, status_code=status.HTTP_201_CREATED)
async def create_agent(
    body: AgentCreate,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    # Enforce slug uniqueness per user to prevent duplicate records.
    base_slug = body.slug
    slug = base_slug
    existing = await db.execute(
        select(Agent.slug).where(Agent.user_id == user.id, Agent.slug.like(f"{base_slug}%"))
    )
    taken = {s for s in existing.scalars().all()}
    if slug in taken:
        i = 2
        while f"{base_slug}-{i}" in taken:
            i += 1
        slug = f"{base_slug}-{i}"

    agent = Agent(
        name=body.name,
        slug=slug,
        description=body.description,
        system_prompt=body.systemPrompt,
        tags=body.tags,
        platforms=body.platforms,
        user_id=user.id,
        owner=body.owner,
        team=body.team,
        oncall=body.oncall,
        capability=body.capability,
        version=body.version,
        lifecycle=body.lifecycle,
        dependencies=body.dependencies.model_dump() if body.dependencies else None,
        access_scope=body.accessScope,
        guardrails=body.guardrails,
        compliance=body.compliance.model_dump() if body.compliance else None,
        capability_spec=body.capabilitySpec.model_dump() if body.capabilitySpec else None,
        risk_tier=body.riskTier,
        data_classifications=body.dataClassifications,
        source_platform=body.sourcePlatform,
        protection_status=body.protectionStatus,
        capture_style=body.captureStyle,
        policy=body.policy.model_dump() if body.policy else PolicySchema().model_dump(),
    )
    db.add(agent)
    await db.flush()

    snap = AgentSnapshot(agent_id=agent.id, data=_snapshot_data(agent))
    db.add(snap)
    await db.flush()

    event = AuditEvent(
        agent_id=agent.id,
        actor=user.email,
        action="created",
        summary=f"Registered as {agent.lifecycle}",
        snapshot_id=snap.id,
    )
    db.add(event)
    await db.commit()

    refreshed = await db.execute(
        select(Agent).where(Agent.id == agent.id).options(*_eager())
    )
    return _agent_to_out(refreshed.scalar_one())


# ── Discovery API (queryable capability contract) ──────────────────────────────

class DiscoveredAgent(BaseModel):
    id: str
    name: str
    slug: str
    capability: str | None = None
    capabilitySpec: dict | None = None
    team: str | None = None
    owner: str | None = None
    lifecycle: str | None = None
    riskTier: str | None = None
    dependencies: dict | None = None
    protectionStatus: str | None = None


@router.get("/discover", response_model=list[DiscoveredAgent])
async def discover_agents(
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
    q: str | None = Query(None, description="Free-text capability search"),
    team: str | None = Query(None),
    lifecycle: str | None = Query(None),
    risk_tier: str | None = Query(None),
):
    """Programmatic lookup so multi-agent systems can find each other at runtime
    against an open contract. Searches capability, name, description, tags."""
    stmt = select(Agent).where(Agent.user_id == user.id)
    if team:
        stmt = stmt.where(Agent.team == team)
    if lifecycle:
        stmt = stmt.where(Agent.lifecycle == lifecycle)
    if risk_tier:
        stmt = stmt.where(Agent.risk_tier == risk_tier)
    result = await db.execute(stmt)
    agents = result.scalars().all()

    if q:
        ql = q.lower()
        def matches(a: Agent) -> bool:
            hay = " ".join(filter(None, [
                a.name, a.slug, a.capability, a.description,
                " ".join(a.tags or []),
            ])).lower()
            return ql in hay
        agents = [a for a in agents if matches(a)]

    return [
        DiscoveredAgent(
            id=a.id, name=a.name, slug=a.slug, capability=a.capability,
            capabilitySpec=a.capability_spec, team=a.team, owner=a.owner,
            lifecycle=a.lifecycle, riskTier=a.risk_tier, dependencies=a.dependencies,
            protectionStatus=a.protection_status,
        )
        for a in agents
    ]


# ── Duplicate detection & merge ────────────────────────────────────────────────

class DuplicateAgent(BaseModel):
    id: str
    name: str
    slug: str
    lifecycle: str | None = None
    protectionStatus: str | None = None
    createdAt: str | None = None
    isJunk: bool = False
    recommendedKeep: bool = False


class DuplicateGroup(BaseModel):
    key: str
    reason: str  # "slug" | "trace-junk"
    agents: list[DuplicateAgent]


class MergeRequest(BaseModel):
    keepId: str
    mergeIds: list[str]


class DedupeRequest(BaseModel):
    removeTraceJunk: bool = True
    dryRun: bool = False


def _dup_agent_out(a: Agent, keep: bool) -> DuplicateAgent:
    return DuplicateAgent(
        id=a.id, name=a.name, slug=a.slug, lifecycle=a.lifecycle,
        protectionStatus=a.protection_status,
        createdAt=a.created_at.isoformat() if a.created_at else None,
        isJunk=_is_trace_junk(a), recommendedKeep=keep,
    )


@router.get("/duplicates", response_model=list[DuplicateGroup])
async def list_duplicates(
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Return groups of duplicate agents: same slug, plus hash-named trace junk."""
    result = await db.execute(
        select(Agent).where(Agent.user_id == user.id).options(*_eager())
    )
    agents = result.scalars().all()

    groups: list[DuplicateGroup] = []

    # 1. Same-slug duplicates.
    by_slug: dict[str, list[Agent]] = {}
    for a in agents:
        by_slug.setdefault(a.slug, []).append(a)
    for slug, group in by_slug.items():
        if len(group) < 2:
            continue
        ranked = sorted(group, key=_dup_score, reverse=True)
        keep_id = ranked[0].id
        groups.append(DuplicateGroup(
            key=slug, reason="slug",
            agents=[_dup_agent_out(a, a.id == keep_id) for a in ranked],
        ))

    # 2. Trace-junk records (only if not already a unique real agent).
    junk = [a for a in agents if _is_trace_junk(a)]
    if junk:
        groups.append(DuplicateGroup(
            key="trace-artifacts", reason="trace-junk",
            agents=[_dup_agent_out(a, False) for a in junk],
        ))

    return groups


async def _absorb(db: AsyncSession, keeper: Agent, victim: Agent):
    """Move a victim's threats/audit onto the keeper, then delete the victim."""
    for t in list(victim.threats or []):
        t.agent_id = keeper.id
    for e in list(victim.audit_log or []):
        e.agent_id = keeper.id
    # snapshots are tied to history; drop them with the victim
    await db.delete(victim)


@router.post("/merge", response_model=AgentOut)
async def merge_agents(
    body: MergeRequest,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Merge one or more duplicate agents into a keeper, preserving threats/audit."""
    res = await db.execute(
        select(Agent).where(Agent.user_id == user.id).options(*_eager())
    )
    agents = {a.id: a for a in res.scalars().all()}
    keeper = agents.get(body.keepId)
    if not keeper:
        raise HTTPException(status_code=404, detail="Keeper agent not found")

    merged = 0
    for mid in body.mergeIds:
        victim = agents.get(mid)
        if not victim or victim.id == keeper.id:
            continue
        await _absorb(db, keeper, victim)
        merged += 1

    if merged:
        db.add(AuditEvent(
            agent_id=keeper.id, actor=user.email, action="updated",
            summary=f"Merged {merged} duplicate record(s) into this agent",
        ))
    await db.commit()

    refreshed = await db.execute(
        select(Agent).where(Agent.id == keeper.id).options(*_eager())
    )
    return _agent_to_out(refreshed.scalar_one())


@router.post("/dedupe")
async def dedupe_fleet(
    body: DedupeRequest,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Auto-merge every same-slug duplicate (keeping the best record) and
    optionally remove hash-named trace junk. Returns a summary."""
    result = await db.execute(
        select(Agent).where(Agent.user_id == user.id).options(*_eager())
    )
    agents = result.scalars().all()

    merged_slugs: list[dict] = []
    removed_junk: list[str] = []
    to_delete: set[str] = set()

    # Same-slug merge.
    by_slug: dict[str, list[Agent]] = {}
    for a in agents:
        by_slug.setdefault(a.slug, []).append(a)
    for slug, group in by_slug.items():
        if len(group) < 2:
            continue
        ranked = sorted(group, key=_dup_score, reverse=True)
        keeper = ranked[0]
        victims = ranked[1:]
        merged_slugs.append({
            "slug": slug, "kept": keeper.id,
            "removed": [v.id for v in victims], "count": len(victims),
        })
        if not body.dryRun:
            for v in victims:
                await _absorb(db, keeper, v)
                to_delete.add(v.id)

    # Trace junk (skip any we already deleted / kept as keeper).
    if body.removeTraceJunk:
        for a in agents:
            if a.id in to_delete:
                continue
            if _is_trace_junk(a):
                removed_junk.append(a.id)
                if not body.dryRun:
                    await db.delete(a)

    if not body.dryRun:
        await db.commit()

    return {
        "dryRun": body.dryRun,
        "mergedSlugGroups": merged_slugs,
        "duplicatesRemoved": sum(g["count"] for g in merged_slugs),
        "traceJunkRemoved": removed_junk,
        "traceJunkCount": len(removed_junk),
    }


@router.get("/{agent_id}", response_model=AgentOut)
async def get_agent(
    agent_id: str,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    result = await db.execute(
        select(Agent)
        .where(Agent.id == agent_id, Agent.user_id == user.id)
        .options(*_eager())
    )
    agent = result.scalar_one_or_none()
    if not agent:
        raise HTTPException(status_code=404, detail="Agent not found")
    return _agent_to_out(agent)


@router.patch("/{agent_id}", response_model=AgentOut)
async def update_agent(
    agent_id: str,
    body: AgentUpdate,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
    summary: str | None = Query(None),
):
    result = await db.execute(
        select(Agent)
        .where(Agent.id == agent_id, Agent.user_id == user.id)
        .options(*_eager())
    )
    agent = result.scalar_one_or_none()
    if not agent:
        raise HTTPException(status_code=404, detail="Agent not found")

    pre_snap = AgentSnapshot(agent_id=agent.id, data=_snapshot_data(agent))
    db.add(pre_snap)
    await db.flush()

    old_lifecycle = agent.lifecycle
    changed_fields: list[str] = []
    update_data = body.model_dump(exclude_unset=True)

    field_map = {
        "systemPrompt": "system_prompt",
        "accessScope": "access_scope",
        "approvedBy": "approved_by",
        "capabilitySpec": "capability_spec",
        "riskTier": "risk_tier",
        "dataClassifications": "data_classifications",
        "sourcePlatform": "source_platform",
        "protectionStatus": "protection_status",
        "captureStyle": "capture_style",
    }

    for key, value in update_data.items():
        db_field = field_map.get(key, key)
        if hasattr(value, "model_dump"):
            value = value.model_dump()
        if getattr(agent, db_field, None) != value:
            changed_fields.append(key)
        setattr(agent, db_field, value)

    new_lifecycle = agent.lifecycle
    action = "updated"
    audit_summary = summary
    if old_lifecycle != new_lifecycle:
        oi = LIFECYCLE_ORDER.index(old_lifecycle) if old_lifecycle in LIFECYCLE_ORDER else 0
        ni = LIFECYCLE_ORDER.index(new_lifecycle) if new_lifecycle in LIFECYCLE_ORDER else 0
        action = "promoted" if ni > oi else "demoted"
        audit_summary = f"{old_lifecycle} → {new_lifecycle}"
    elif not audit_summary:
        if changed_fields:
            display = ", ".join(changed_fields[:6])
            if len(changed_fields) > 6:
                display += "…"
            audit_summary = f"Edited: {display}"
        else:
            audit_summary = "No-op edit"

    event = AuditEvent(
        agent_id=agent.id,
        actor=user.email,
        action=action,
        from_state=old_lifecycle if action != "updated" else None,
        to_state=new_lifecycle if action != "updated" else None,
        summary=audit_summary,
        snapshot_id=pre_snap.id,
    )
    db.add(event)
    await db.commit()

    refreshed = await db.execute(
        select(Agent).where(Agent.id == agent.id).options(*_eager())
    )
    return _agent_to_out(refreshed.scalar_one())


@router.delete("/{agent_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_agent(
    agent_id: str,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    result = await db.execute(
        select(Agent).where(Agent.id == agent_id, Agent.user_id == user.id)
    )
    agent = result.scalar_one_or_none()
    if not agent:
        raise HTTPException(status_code=404, detail="Agent not found")
    await db.delete(agent)
    await db.commit()


@router.post("/{agent_id}/restore/{snapshot_id}", response_model=AgentOut)
async def restore_snapshot(
    agent_id: str,
    snapshot_id: str,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    result = await db.execute(
        select(Agent)
        .where(Agent.id == agent_id, Agent.user_id == user.id)
        .options(*_eager())
    )
    agent = result.scalar_one_or_none()
    if not agent:
        raise HTTPException(status_code=404, detail="Agent not found")

    snap = next((s for s in agent.snapshots if s.id == snapshot_id), None)
    if not snap:
        raise HTTPException(status_code=404, detail="Snapshot not found")

    pre_restore_snap = AgentSnapshot(agent_id=agent.id, data=_snapshot_data(agent))
    db.add(pre_restore_snap)
    await db.flush()

    data = snap.data
    for key in ["name", "slug", "description", "owner", "team", "oncall", "capability",
                "version", "lifecycle", "guardrails"]:
        if key in data:
            setattr(agent, key, data[key])
    for key in ["tags", "platforms", "dependencies", "compliance", "policy",
                "data_classifications", "access_scope", "capability_spec"]:
        if key in data:
            setattr(agent, key, data[key])
    if "systemPrompt" in data:
        agent.system_prompt = data["systemPrompt"]
    if "riskTier" in data:
        agent.risk_tier = data["riskTier"]
    if "protectionStatus" in data:
        agent.protection_status = data["protectionStatus"]

    event = AuditEvent(
        agent_id=agent.id,
        actor=user.email,
        action="restored",
        summary=f"Restored snapshot from {snap.at.isoformat() if snap.at else 'unknown'}",
        snapshot_id=pre_restore_snap.id,
    )
    db.add(event)
    await db.commit()

    refreshed = await db.execute(
        select(Agent).where(Agent.id == agent.id).options(*_eager())
    )
    return _agent_to_out(refreshed.scalar_one())
